include: package:flutter_lints/flutter.yaml


analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: ignore
    constant_identifier_names: ignore


linter:
  rules:
    parameter_assignments: false
    unnecessary_statements: true
    avoid_print: true
    sized_box_for_whitespace: true
    constant_identifier_names: false
    avoid_unused_constructor_parameters: true