name: fidibo_paper
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.7+9

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #core library
  flutter_lints: ^2.0.1
  get_it: ^7.6.0
  collection: ^1.17.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  logger: ^1.3.0
  get_storage: ^2.1.1
  cupertino_icons: ^1.0.2
  intl:
  go_router: ^9.0.3

  #other library
  expand_tap_area: ^1.1.1
  flutter_animated_dialog: ^2.0.1
  audioplayers: ^4.0.1
  flutter_svg: ^2.0.6
  flutter_native_splash: ^2.3.0
  loading_animation_widget: ^1.2.0+4
  wakelock:
  lottie: ^2.2.0
  animated_theme_switcher: ^2.0.7
  flutter_multi_formatter: ^2.10.1
  flutter_vibrate: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  build_runner:


flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "images/logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/

  fonts:
    - family: iranSans
      fonts:
        - asset: fonts/iran_sans/iran_sans_fa_num_ultra_light_200.ttf
          weight: 200
        - asset: fonts/iran_sans/iran_sans_fa_num_light_300.ttf
          weight: 300
        - asset: fonts/iran_sans/iran_sans_fa_num_medium_400.ttf
          weight: 400
        - asset: fonts/iran_sans/iran_sans_fa_num_500.ttf
          weight: 500
        - asset: fonts/iran_sans/iran_sans_fa_num_bold_700.ttf
          weight: 700
        - asset: fonts/iran_sans/iran_sans_fa_num_black_900.ttf
          weight: 900